version: '1.0'
name: gigashop_prod
services:
  client:
    build:
      context: ./client
      target: production
    container_name: client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      REACT_APP_NGROK_SERVER_URL: https://5be7-188-163-19-100.ngrok-free.app
      REACT_APP_NGROK_CLIENT_URL: http://localhost:3000
      REACT_APP_API_URL: /api
    depends_on:
      - server

  server:
    build:
      context: ./server
      target: production
    container_name: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    environment:
      DB_NAME: gigashop
      DB_USER: gigashop
      DB_PASSWORD: root
      DB_PORT: 5432
      DB_HOST: database
      CONNECT_TIMEOUT: 5000
      CONNECT_RETRIES: 10
      CLOUDINARY_SECRET: dxCEJghbMzdX0gtVpZUqn43eEOU
      LIQPAY_TEST_PUBLIC_KEY: sandbox_i27206268381
      LIQPAY_TEST_PRIVATE_KEY: sandbox_3DM1ZMsYJPj9NMgSa73gsG9HEN88pvk14APy9hfu
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    ports:
      - 5001:5432
    environment:
      POSTGRES_DB: gigashop
      POSTGRES_USER: gigashop
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/var/lib/postgresql/data