version: '1.1'
name: gigashop_dev
services:
  server:
    build:
      context: ./server
      target: development
    container_name: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./static:/usr/src/app/static
    ports:
      - 5000:5000
    command: npm run dev
    environment:
      DB_NAME: gigashop
      DB_USER: gigashop
      DB_PASSWORD: root
      DB_PORT: 5432
      DB_HOST: database
    depends_on:
      - database
  database:
    container_name: database
    image: postgres
    ports:
      - 5001:5432
    environment:
      POSTGRES_USER: gigashop
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gigashop
    volumes:
      - ./data:/var/lib/postgresql/data