version: '1.1'
name: gigashop_dev
services:
  client:
    build:
      context: ./client
      target: development
    container_name: client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - server
    command:
      - npm start

  server:
    build:
      context: ./server
      target: development
    container_name: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./static:/usr/src/app/static
    ports:
      - 5000:5000
    command: npm run dev
    environment:
      DB_NAME: gigashop
      DB_USER: gigashop
      DB_PASSWORD: root
      DB_PORT: 5432
      DB_HOST: database
      CONNECT_TIMEOUT: 5000
      CONNECT_RETRIES: 10
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    ports:
      - 5001:5432
    environment:
      POSTGRES_DB: gigashop
      POSTGRES_USER: gigashop
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/var/lib/postgresql/data