# .github/workflows/deploy.yml

name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '355.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Tag Docker Images
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigashop-server ./server
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigashop-client ./client
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigashop-server gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigashop-server:v1.0
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigashop-client gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigashop-client:v1.0

      - name: Push Docker Images to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigashop-server:v1.0
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigashop-client:v1.0

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials gigashop-cluster --zone europe-west1-b --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml